# Generated by Grammarinator 26.1

from math import inf
from typing import Callable, ClassVar
from grammarinator.runtime import *

class cookiecutter_caseGenerator(Generator):


    def case_file(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'case_file', parent) as rule:
            current = rule.current
            self.case_object(parent=current)
        return current

    def case_object(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'case_object', parent) as rule:
            current = rule.current
            self._reserve(138, self.T__0, parent=current)
            self._reserve(137, self.T__1, parent=current)
            self._reserve(136, self.T__2, parent=current)
            self._reserve(135, self.execution_mode, parent=current)
            self._reserve(134, self.T__3, parent=current)
            self._reserve(133, self.T__4, parent=current)
            self._reserve(132, self.T__2, parent=current)
            self._reserve(131, self.template_source, parent=current)
            self._reserve(130, self.T__3, parent=current)
            self._reserve(129, self.T__5, parent=current)
            self._reserve(128, self.T__2, parent=current)
            self._reserve(37, self.template_object, parent=current)
            self._reserve(36, self.T__3, parent=current)
            self._reserve(35, self.T__6, parent=current)
            self._reserve(34, self.T__2, parent=current)
            self._reserve(1, self.invocation_object, parent=current)
            self.T__7(parent=current)
        return current

    def execution_mode(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'execution_mode', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[0], 0, cookiecutter_caseGenerator._alt_conds[0]) as alt0:
                current = rule.current
                [self.T__8, self.T__9][alt0()](parent=current)
            current = rule.current
        return current

    def template_source(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'template_source', parent) as rule:
            current = rule.current
            self.T__10(parent=current)
        return current

    def template_object(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'template_object', parent) as rule:
            current = rule.current
            self._reserve(90, self.T__0, parent=current)
            self._reserve(89, self.T__11, parent=current)
            self._reserve(88, self.T__2, parent=current)
            self._reserve(87, self.root_name, parent=current)
            self._reserve(86, self.T__3, parent=current)
            self._reserve(85, self.T__12, parent=current)
            self._reserve(84, self.T__2, parent=current)
            self._reserve(51, self.cookiecutter_json_object, parent=current)
            self._reserve(50, self.T__3, parent=current)
            self._reserve(49, self.T__13, parent=current)
            self._reserve(48, self.T__2, parent=current)
            self._reserve(47, self.prompts_object, parent=current)
            self._reserve(46, self.T__3, parent=current)
            self._reserve(45, self.T__14, parent=current)
            self._reserve(44, self.T__2, parent=current)
            self._reserve(43, self.copy_without_render_array, parent=current)
            self._reserve(42, self.T__3, parent=current)
            self._reserve(41, self.T__15, parent=current)
            self._reserve(40, self.T__2, parent=current)
            self._reserve(39, self.newline_value, parent=current)
            self._reserve(38, self.T__3, parent=current)
            self._reserve(37, self.T__16, parent=current)
            self._reserve(36, self.T__2, parent=current)
            self._reserve(21, self.files_array, parent=current)
            self._reserve(20, self.T__3, parent=current)
            self._reserve(19, self.T__17, parent=current)
            self._reserve(18, self.T__2, parent=current)
            self._reserve(5, self.hooks_object, parent=current)
            self._reserve(4, self.T__3, parent=current)
            self._reserve(3, self.T__18, parent=current)
            self._reserve(2, self.T__2, parent=current)
            self._reserve(1, self.nested_templates_value, parent=current)
            self.T__7(parent=current)
        return current

    def root_name(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'root_name', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[0], 0, cookiecutter_caseGenerator._alt_conds[0]) as alt0:
                current = rule.current
                [self.T__19, self.T__20][alt0()](parent=current)
            current = rule.current
        return current

    def cookiecutter_json_object(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'cookiecutter_json_object', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[1], 0, cookiecutter_caseGenerator._alt_conds[0]) as alt0:
                current = rule.current
                choice0 = alt0()
                if choice0 == 0:
                    self._reserve(32, self.T__0, parent=current)
                    self._reserve(31, self.T__21, parent=current)
                    self._reserve(30, self.T__2, parent=current)
                    self._reserve(29, self.project_name_value, parent=current)
                    self._reserve(28, self.T__3, parent=current)
                    self._reserve(27, self.T__22, parent=current)
                    self._reserve(26, self.T__2, parent=current)
                    self._reserve(25, self.repo_name_value, parent=current)
                    self._reserve(24, self.T__3, parent=current)
                    self._reserve(23, self.T__23, parent=current)
                    self._reserve(22, self.T__2, parent=current)
                    self._reserve(21, self.json_bool, parent=current)
                    self._reserve(20, self.T__3, parent=current)
                    self._reserve(19, self.T__24, parent=current)
                    self._reserve(18, self.T__2, parent=current)
                    self._reserve(13, self.choice_array, parent=current)
                    self._reserve(12, self.T__3, parent=current)
                    self._reserve(11, self.T__25, parent=current)
                    self._reserve(10, self.T__2, parent=current)
                    self._reserve(1, self.database_object, parent=current)
                    self.T__7(parent=current)
                elif choice0 == 1:
                    self._reserve(32, self.T__0, parent=current)
                    self._reserve(31, self.T__21, parent=current)
                    self._reserve(30, self.T__2, parent=current)
                    self._reserve(29, self.project_name_value, parent=current)
                    self._reserve(28, self.T__3, parent=current)
                    self._reserve(27, self.T__22, parent=current)
                    self._reserve(26, self.T__2, parent=current)
                    self._reserve(25, self.repo_name_value, parent=current)
                    self._reserve(24, self.T__3, parent=current)
                    self._reserve(23, self.T__26, parent=current)
                    self._reserve(22, self.T__2, parent=current)
                    self._reserve(13, self.feature_flag_dict, parent=current)
                    self._reserve(12, self.T__3, parent=current)
                    self._reserve(11, self.T__27, parent=current)
                    self._reserve(10, self.T__2, parent=current)
                    self._reserve(1, self.owner_object, parent=current)
                    self.T__7(parent=current)
            current = rule.current
        return current

    def project_name_value(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'project_name_value', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[2], 0, cookiecutter_caseGenerator._alt_conds[1]) as alt0:
                current = rule.current
                [self.T__28, self.T__29, self.T__30, self.T__31][alt0()](parent=current)
            current = rule.current
        return current

    def repo_name_value(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'repo_name_value', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[0], 0, cookiecutter_caseGenerator._alt_conds[0]) as alt0:
                current = rule.current
                [self.T__32, self.T__33][alt0()](parent=current)
            current = rule.current
        return current

    def database_object(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'database_object', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[3], 0, cookiecutter_caseGenerator._alt_conds[0]) as alt0:
                current = rule.current
                choice0 = alt0()
                if choice0 == 0:
                    self._reserve(8, self.T__0, parent=current)
                    self._reserve(7, self.T__34, parent=current)
                    self._reserve(6, self.T__2, parent=current)
                    self._reserve(5, self.T__35, parent=current)
                    self._reserve(4, self.T__3, parent=current)
                    self._reserve(3, self.T__36, parent=current)
                    self._reserve(2, self.T__2, parent=current)
                    self._reserve(1, self.T__37, parent=current)
                    self.T__7(parent=current)
                elif choice0 == 1:
                    self._reserve(8, self.T__0, parent=current)
                    self._reserve(7, self.T__34, parent=current)
                    self._reserve(6, self.T__2, parent=current)
                    self._reserve(5, self.T__38, parent=current)
                    self._reserve(4, self.T__3, parent=current)
                    self._reserve(3, self.T__36, parent=current)
                    self._reserve(2, self.T__2, parent=current)
                    self._reserve(1, self.T__37, parent=current)
                    self.T__7(parent=current)
            current = rule.current
        return current

    def feature_flag_dict(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'feature_flag_dict', parent) as rule:
            current = rule.current
            self._reserve(8, self.T__0, parent=current)
            self._reserve(7, self.T__39, parent=current)
            self._reserve(6, self.T__2, parent=current)
            self._reserve(5, self.json_bool, parent=current)
            self._reserve(4, self.T__3, parent=current)
            self._reserve(3, self.T__40, parent=current)
            self._reserve(2, self.T__2, parent=current)
            self._reserve(1, self.json_bool, parent=current)
            self.T__7(parent=current)
        return current

    def owner_object(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'owner_object', parent) as rule:
            current = rule.current
            self._reserve(8, self.T__0, parent=current)
            self._reserve(7, self.T__41, parent=current)
            self._reserve(6, self.T__2, parent=current)
            self._reserve(5, self.T__42, parent=current)
            self._reserve(4, self.T__3, parent=current)
            self._reserve(3, self.T__43, parent=current)
            self._reserve(2, self.T__2, parent=current)
            self._reserve(1, self.T__44, parent=current)
            self.T__7(parent=current)
        return current

    def prompts_object(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'prompts_object', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[4], 0, cookiecutter_caseGenerator._alt_conds[2]) as alt0:
                current = rule.current
                choice0 = alt0()
                if choice0 == 0:
                    self.T__45(parent=current)
                elif choice0 == 1:
                    self._reserve(16, self.T__0, parent=current)
                    self._reserve(15, self.T__21, parent=current)
                    self._reserve(14, self.T__2, parent=current)
                    self._reserve(13, self.T__46, parent=current)
                    self._reserve(12, self.T__3, parent=current)
                    self._reserve(11, self.T__23, parent=current)
                    self._reserve(10, self.T__2, parent=current)
                    self._reserve(9, self.T__47, parent=current)
                    self._reserve(8, self.T__3, parent=current)
                    self._reserve(7, self.T__24, parent=current)
                    self._reserve(6, self.T__2, parent=current)
                    self._reserve(5, self.T__48, parent=current)
                    self._reserve(4, self.T__3, parent=current)
                    self._reserve(3, self.T__25, parent=current)
                    self._reserve(2, self.T__2, parent=current)
                    self._reserve(1, self.T__49, parent=current)
                    self.T__7(parent=current)
                elif choice0 == 2:
                    self._reserve(8, self.T__0, parent=current)
                    self._reserve(7, self.T__21, parent=current)
                    self._reserve(6, self.T__2, parent=current)
                    self._reserve(5, self.T__50, parent=current)
                    self._reserve(4, self.T__3, parent=current)
                    self._reserve(3, self.T__27, parent=current)
                    self._reserve(2, self.T__2, parent=current)
                    self._reserve(1, self.T__51, parent=current)
                    self.T__7(parent=current)
            current = rule.current
        return current

    def copy_without_render_array(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'copy_without_render_array', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[5], 0, cookiecutter_caseGenerator._alt_conds[2]) as alt0:
                current = rule.current
                choice0 = alt0()
                if choice0 == 0:
                    self.T__52(parent=current)
                elif choice0 == 1:
                    self._reserve(2, self.T__53, parent=current)
                    self._reserve(1, self.T__54, parent=current)
                    self.T__55(parent=current)
                elif choice0 == 2:
                    self._reserve(2, self.T__53, parent=current)
                    self._reserve(1, self.T__56, parent=current)
                    self.T__55(parent=current)
            current = rule.current
        return current

    def newline_value(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'newline_value', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[6], 0, cookiecutter_caseGenerator._alt_conds[2]) as alt0:
                current = rule.current
                [self.T__57, self.T__58, self.T__59][alt0()](parent=current)
            current = rule.current
        return current

    def files_array(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'files_array', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[7], 0, cookiecutter_caseGenerator._alt_conds[2]) as alt0:
                current = rule.current
                choice0 = alt0()
                if choice0 == 0:
                    self._reserve(14, self.T__53, parent=current)
                    self._reserve(1, self.file_entry, parent=current)
                    self.T__55(parent=current)
                elif choice0 == 1:
                    self._reserve(28, self.T__53, parent=current)
                    self._reserve(15, self.file_entry, parent=current)
                    self._reserve(14, self.T__3, parent=current)
                    self._reserve(1, self.file_entry, parent=current)
                    self.T__55(parent=current)
                elif choice0 == 2:
                    self._reserve(42, self.T__53, parent=current)
                    self._reserve(29, self.file_entry, parent=current)
                    self._reserve(28, self.T__3, parent=current)
                    self._reserve(15, self.file_entry, parent=current)
                    self._reserve(14, self.T__3, parent=current)
                    self._reserve(1, self.file_entry, parent=current)
                    self.T__55(parent=current)
            current = rule.current
        return current

    def file_entry(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'file_entry', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[8], 0, cookiecutter_caseGenerator._alt_conds[0]) as alt0:
                current = rule.current
                choice0 = alt0()
                if choice0 == 0:
                    self._reserve(12, self.T__0, parent=current)
                    self._reserve(11, self.T__60, parent=current)
                    self._reserve(10, self.T__2, parent=current)
                    self._reserve(9, self.path_expr, parent=current)
                    self._reserve(8, self.T__3, parent=current)
                    self._reserve(7, self.T__61, parent=current)
                    self._reserve(6, self.T__2, parent=current)
                    self._reserve(5, self.T__62, parent=current)
                    self._reserve(4, self.T__3, parent=current)
                    self._reserve(3, self.T__63, parent=current)
                    self._reserve(2, self.T__2, parent=current)
                    self._reserve(1, self.text_contents, parent=current)
                    self.T__7(parent=current)
                elif choice0 == 1:
                    self._reserve(12, self.T__0, parent=current)
                    self._reserve(11, self.T__60, parent=current)
                    self._reserve(10, self.T__2, parent=current)
                    self._reserve(9, self.binary_path_expr, parent=current)
                    self._reserve(8, self.T__3, parent=current)
                    self._reserve(7, self.T__61, parent=current)
                    self._reserve(6, self.T__2, parent=current)
                    self._reserve(5, self.T__64, parent=current)
                    self._reserve(4, self.T__3, parent=current)
                    self._reserve(3, self.T__63, parent=current)
                    self._reserve(2, self.T__2, parent=current)
                    self._reserve(1, self.binary_contents, parent=current)
                    self.T__7(parent=current)
            current = rule.current
        return current

    def path_expr(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'path_expr', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[9], 0, cookiecutter_caseGenerator._alt_conds[3]) as alt0:
                current = rule.current
                [self.T__65, self.T__66, self.T__67, self.T__68, self.T__69, self.T__70, self.T__71][alt0()](parent=current)
            current = rule.current
        return current

    def binary_path_expr(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'binary_path_expr', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[0], 0, cookiecutter_caseGenerator._alt_conds[0]) as alt0:
                current = rule.current
                [self.T__72, self.T__73][alt0()](parent=current)
            current = rule.current
        return current

    def text_contents(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'text_contents', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[10], 0, cookiecutter_caseGenerator._alt_conds[4]) as alt0:
                current = rule.current
                [self.T__74, self.T__75, self.T__76, self.T__77, self.T__78][alt0()](parent=current)
            current = rule.current
        return current

    def binary_contents(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'binary_contents', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[0], 0, cookiecutter_caseGenerator._alt_conds[0]) as alt0:
                current = rule.current
                [self.T__79, self.T__80][alt0()](parent=current)
            current = rule.current
        return current

    def hooks_object(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'hooks_object', parent) as rule:
            current = rule.current
            self._reserve(12, self.T__0, parent=current)
            self._reserve(11, self.T__81, parent=current)
            self._reserve(10, self.T__2, parent=current)
            self._reserve(9, self.hook_script, parent=current)
            self._reserve(8, self.T__3, parent=current)
            self._reserve(7, self.T__82, parent=current)
            self._reserve(6, self.T__2, parent=current)
            self._reserve(5, self.hook_script, parent=current)
            self._reserve(4, self.T__3, parent=current)
            self._reserve(3, self.T__83, parent=current)
            self._reserve(2, self.T__2, parent=current)
            self._reserve(1, self.hook_script, parent=current)
            self.T__7(parent=current)
        return current

    def hook_script(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'hook_script', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[6], 0, cookiecutter_caseGenerator._alt_conds[2]) as alt0:
                current = rule.current
                [self.T__59, self.T__84, self.T__85][alt0()](parent=current)
            current = rule.current
        return current

    def nested_templates_value(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'nested_templates_value', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[11], 0, cookiecutter_caseGenerator._alt_conds[0]) as alt0:
                current = rule.current
                choice0 = alt0()
                if choice0 == 0:
                    self.T__59(parent=current)
                elif choice0 == 1:
                    self._reserve(36, self.T__53, parent=current)
                    self._reserve(19, self.nested_template_entry, parent=current)
                    self._reserve(18, self.T__3, parent=current)
                    self._reserve(1, self.nested_template_entry, parent=current)
                    self.T__55(parent=current)
            current = rule.current
        return current

    def nested_template_entry(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'nested_template_entry', parent) as rule:
            current = rule.current
            self._reserve(16, self.T__0, parent=current)
            self._reserve(15, self.T__86, parent=current)
            self._reserve(14, self.T__2, parent=current)
            self._reserve(13, self.nested_key, parent=current)
            self._reserve(12, self.T__3, parent=current)
            self._reserve(11, self.T__60, parent=current)
            self._reserve(10, self.T__2, parent=current)
            self._reserve(9, self.nested_path, parent=current)
            self._reserve(8, self.T__3, parent=current)
            self._reserve(7, self.T__87, parent=current)
            self._reserve(6, self.T__2, parent=current)
            self._reserve(5, self.nested_title, parent=current)
            self._reserve(4, self.T__3, parent=current)
            self._reserve(3, self.T__88, parent=current)
            self._reserve(2, self.T__2, parent=current)
            self._reserve(1, self.nested_description, parent=current)
            self.T__7(parent=current)
        return current

    def nested_key(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'nested_key', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[0], 0, cookiecutter_caseGenerator._alt_conds[0]) as alt0:
                current = rule.current
                [self.T__89, self.T__90][alt0()](parent=current)
            current = rule.current
        return current

    def nested_path(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'nested_path', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[0], 0, cookiecutter_caseGenerator._alt_conds[0]) as alt0:
                current = rule.current
                [self.T__91, self.T__92][alt0()](parent=current)
            current = rule.current
        return current

    def nested_title(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'nested_title', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[0], 0, cookiecutter_caseGenerator._alt_conds[0]) as alt0:
                current = rule.current
                [self.T__93, self.T__94][alt0()](parent=current)
            current = rule.current
        return current

    def nested_description(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'nested_description', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[0], 0, cookiecutter_caseGenerator._alt_conds[0]) as alt0:
                current = rule.current
                [self.T__95, self.T__96][alt0()](parent=current)
            current = rule.current
        return current

    def invocation_object(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'invocation_object', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[12], 0, cookiecutter_caseGenerator._alt_conds[0]) as alt0:
                current = rule.current
                choice0 = alt0()
                if choice0 == 0:
                    self._reserve(32, self.T__0, parent=current)
                    self._reserve(31, self.T__97, parent=current)
                    self._reserve(30, self.T__2, parent=current)
                    self._reserve(29, self.T__98, parent=current)
                    self._reserve(28, self.T__3, parent=current)
                    self._reserve(27, self.T__99, parent=current)
                    self._reserve(26, self.T__2, parent=current)
                    self._reserve(25, self.extra_context_object, parent=current)
                    self._reserve(24, self.T__3, parent=current)
                    self._reserve(23, self.T__100, parent=current)
                    self._reserve(22, self.T__2, parent=current)
                    self._reserve(21, self.T__59, parent=current)
                    self._reserve(20, self.T__3, parent=current)
                    self._reserve(19, self.T__101, parent=current)
                    self._reserve(18, self.T__2, parent=current)
                    self._reserve(17, self.json_bool, parent=current)
                    self._reserve(16, self.T__3, parent=current)
                    self._reserve(15, self.T__102, parent=current)
                    self._reserve(14, self.T__2, parent=current)
                    self._reserve(13, self.json_bool, parent=current)
                    self._reserve(12, self.T__3, parent=current)
                    self._reserve(11, self.T__103, parent=current)
                    self._reserve(10, self.T__2, parent=current)
                    self._reserve(9, self.json_bool, parent=current)
                    self._reserve(8, self.T__3, parent=current)
                    self._reserve(7, self.T__104, parent=current)
                    self._reserve(6, self.T__2, parent=current)
                    self._reserve(5, self.json_bool, parent=current)
                    self._reserve(4, self.T__3, parent=current)
                    self._reserve(3, self.T__105, parent=current)
                    self._reserve(2, self.T__2, parent=current)
                    self._reserve(1, self.output_dir_state, parent=current)
                    self.T__7(parent=current)
                elif choice0 == 1:
                    self._reserve(32, self.T__0, parent=current)
                    self._reserve(31, self.T__97, parent=current)
                    self._reserve(30, self.T__2, parent=current)
                    self._reserve(29, self.T__106, parent=current)
                    self._reserve(28, self.T__3, parent=current)
                    self._reserve(27, self.T__99, parent=current)
                    self._reserve(26, self.T__2, parent=current)
                    self._reserve(25, self.T__45, parent=current)
                    self._reserve(24, self.T__3, parent=current)
                    self._reserve(23, self.T__100, parent=current)
                    self._reserve(22, self.T__2, parent=current)
                    self._reserve(21, self.replay_value, parent=current)
                    self._reserve(20, self.T__3, parent=current)
                    self._reserve(19, self.T__101, parent=current)
                    self._reserve(18, self.T__2, parent=current)
                    self._reserve(17, self.json_bool, parent=current)
                    self._reserve(16, self.T__3, parent=current)
                    self._reserve(15, self.T__102, parent=current)
                    self._reserve(14, self.T__2, parent=current)
                    self._reserve(13, self.json_bool, parent=current)
                    self._reserve(12, self.T__3, parent=current)
                    self._reserve(11, self.T__103, parent=current)
                    self._reserve(10, self.T__2, parent=current)
                    self._reserve(9, self.json_bool, parent=current)
                    self._reserve(8, self.T__3, parent=current)
                    self._reserve(7, self.T__104, parent=current)
                    self._reserve(6, self.T__2, parent=current)
                    self._reserve(5, self.json_bool, parent=current)
                    self._reserve(4, self.T__3, parent=current)
                    self._reserve(3, self.T__105, parent=current)
                    self._reserve(2, self.T__2, parent=current)
                    self._reserve(1, self.output_dir_state, parent=current)
                    self.T__7(parent=current)
            current = rule.current
        return current

    def extra_context_object(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'extra_context_object', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[13], 0, cookiecutter_caseGenerator._alt_conds[2]) as alt0:
                current = rule.current
                choice0 = alt0()
                if choice0 == 0:
                    self.T__45(parent=current)
                elif choice0 == 1:
                    self._reserve(4, self.T__0, parent=current)
                    self._reserve(3, self.T__21, parent=current)
                    self._reserve(2, self.T__2, parent=current)
                    self._reserve(1, self.T__107, parent=current)
                    self.T__7(parent=current)
                elif choice0 == 2:
                    self._reserve(4, self.T__0, parent=current)
                    self._reserve(3, self.T__23, parent=current)
                    self._reserve(2, self.T__2, parent=current)
                    self._reserve(1, self.T__108, parent=current)
                    self.T__7(parent=current)
            current = rule.current
        return current

    def replay_value(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'replay_value', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[14], 0, cookiecutter_caseGenerator._alt_conds[0]) as alt0:
                current = rule.current
                choice0 = alt0()
                if choice0 == 0:
                    self.T__59(parent=current)
                elif choice0 == 1:
                    self._reserve(16, self.T__0, parent=current)
                    self._reserve(15, self.T__109, parent=current)
                    self._reserve(14, self.T__2, parent=current)
                    self._reserve(13, self.T__0, parent=current)
                    self._reserve(12, self.T__21, parent=current)
                    self._reserve(11, self.T__2, parent=current)
                    self._reserve(10, self.T__30, parent=current)
                    self._reserve(9, self.T__3, parent=current)
                    self._reserve(8, self.T__22, parent=current)
                    self._reserve(7, self.T__2, parent=current)
                    self._reserve(6, self.T__110, parent=current)
                    self._reserve(5, self.T__3, parent=current)
                    self._reserve(4, self.T__23, parent=current)
                    self._reserve(3, self.T__2, parent=current)
                    self._reserve(2, self.T__98, parent=current)
                    self._reserve(1, self.T__7, parent=current)
                    self.T__7(parent=current)
            current = rule.current
        return current

    def choice_array(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'choice_array', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[15], 0, cookiecutter_caseGenerator._alt_conds[0]) as alt0:
                current = rule.current
                choice0 = alt0()
                if choice0 == 0:
                    self._reserve(6, self.T__53, parent=current)
                    self._reserve(5, self.T__111, parent=current)
                    self._reserve(4, self.T__3, parent=current)
                    self._reserve(3, self.T__112, parent=current)
                    self._reserve(2, self.T__3, parent=current)
                    self._reserve(1, self.T__113, parent=current)
                    self.T__55(parent=current)
                elif choice0 == 1:
                    self._reserve(4, self.T__53, parent=current)
                    self._reserve(3, self.T__114, parent=current)
                    self._reserve(2, self.T__3, parent=current)
                    self._reserve(1, self.T__111, parent=current)
                    self.T__55(parent=current)
            current = rule.current
        return current

    def output_dir_state(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'output_dir_state', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[6], 0, cookiecutter_caseGenerator._alt_conds[2]) as alt0:
                current = rule.current
                [self.T__115, self.T__116, self.T__117][alt0()](parent=current)
            current = rule.current
        return current

    def json_bool(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'json_bool', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, cookiecutter_caseGenerator._alt_sizes[0], 0, cookiecutter_caseGenerator._alt_conds[0]) as alt0:
                current = rule.current
                [self.T__98, self.T__106][alt0()](parent=current)
            current = rule.current
        return current

    def T__0(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__0', parent, True) as rule:
            current = rule.current
            current.src += '{'
        return current

    def T__1(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__1', parent, True) as rule:
            current = rule.current
            current.src += '\"mode\"'
        return current

    def T__2(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__2', parent, True) as rule:
            current = rule.current
            current.src += ':'
        return current

    def T__3(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__3', parent, True) as rule:
            current = rule.current
            current.src += ','
        return current

    def T__4(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__4', parent, True) as rule:
            current = rule.current
            current.src += '\"template_source\"'
        return current

    def T__5(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__5', parent, True) as rule:
            current = rule.current
            current.src += '\"template\"'
        return current

    def T__6(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__6', parent, True) as rule:
            current = rule.current
            current.src += '\"invocation\"'
        return current

    def T__7(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__7', parent, True) as rule:
            current = rule.current
            current.src += '}'
        return current

    def T__8(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__8', parent, True) as rule:
            current = rule.current
            current.src += '\"cli\"'
        return current

    def T__9(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__9', parent, True) as rule:
            current = rule.current
            current.src += '\"api\"'
        return current

    def T__10(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__10', parent, True) as rule:
            current = rule.current
            current.src += '\"local\"'
        return current

    def T__11(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__11', parent, True) as rule:
            current = rule.current
            current.src += '\"root_name\"'
        return current

    def T__12(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__12', parent, True) as rule:
            current = rule.current
            current.src += '\"cookiecutter_json\"'
        return current

    def T__13(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__13', parent, True) as rule:
            current = rule.current
            current.src += '\"prompts\"'
        return current

    def T__14(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__14', parent, True) as rule:
            current = rule.current
            current.src += '\"copy_without_render\"'
        return current

    def T__15(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__15', parent, True) as rule:
            current = rule.current
            current.src += '\"new_lines\"'
        return current

    def T__16(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__16', parent, True) as rule:
            current = rule.current
            current.src += '\"files\"'
        return current

    def T__17(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__17', parent, True) as rule:
            current = rule.current
            current.src += '\"hooks\"'
        return current

    def T__18(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__18', parent, True) as rule:
            current = rule.current
            current.src += '\"nested_templates\"'
        return current

    def T__19(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__19', parent, True) as rule:
            current = rule.current
            current.src += '\"{{cookiecutter.repo_name}}\"'
        return current

    def T__20(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__20', parent, True) as rule:
            current = rule.current
            current.src += '\"{{cookiecutter.project_name}}\"'
        return current

    def T__21(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__21', parent, True) as rule:
            current = rule.current
            current.src += '\"project_name\"'
        return current

    def T__22(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__22', parent, True) as rule:
            current = rule.current
            current.src += '\"repo_name\"'
        return current

    def T__23(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__23', parent, True) as rule:
            current = rule.current
            current.src += '\"use_docker\"'
        return current

    def T__24(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__24', parent, True) as rule:
            current = rule.current
            current.src += '\"license\"'
        return current

    def T__25(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__25', parent, True) as rule:
            current = rule.current
            current.src += '\"database\"'
        return current

    def T__26(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__26', parent, True) as rule:
            current = rule.current
            current.src += '\"feature_flags\"'
        return current

    def T__27(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__27', parent, True) as rule:
            current = rule.current
            current.src += '\"owner\"'
        return current

    def T__28(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__28', parent, True) as rule:
            current = rule.current
            current.src += '\"Example Project\"'
        return current

    def T__29(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__29', parent, True) as rule:
            current = rule.current
            current.src += '\"Cookie Lab\"'
        return current

    def T__30(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__30', parent, True) as rule:
            current = rule.current
            current.src += '\"Replay Project\"'
        return current

    def T__31(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__31', parent, True) as rule:
            current = rule.current
            current.src += '\"Broken Value\"'
        return current

    def T__32(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__32', parent, True) as rule:
            current = rule.current
            current.src += '\"{{ cookiecutter.project_name|lower }}\"'
        return current

    def T__33(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__33', parent, True) as rule:
            current = rule.current
            current.src += '\"{{ cookiecutter.project_name }}_pkg\"'
        return current

    def T__34(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__34', parent, True) as rule:
            current = rule.current
            current.src += '\"engine\"'
        return current

    def T__35(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__35', parent, True) as rule:
            current = rule.current
            current.src += '\"sqlite\"'
        return current

    def T__36(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__36', parent, True) as rule:
            current = rule.current
            current.src += '\"port\"'
        return current

    def T__37(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__37', parent, True) as rule:
            current = rule.current
            current.src += '\"5432\"'
        return current

    def T__38(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__38', parent, True) as rule:
            current = rule.current
            current.src += '\"postgres\"'
        return current

    def T__39(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__39', parent, True) as rule:
            current = rule.current
            current.src += '\"docs\"'
        return current

    def T__40(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__40', parent, True) as rule:
            current = rule.current
            current.src += '\"ci\"'
        return current

    def T__41(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__41', parent, True) as rule:
            current = rule.current
            current.src += '\"team\"'
        return current

    def T__42(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__42', parent, True) as rule:
            current = rule.current
            current.src += '\"platform\"'
        return current

    def T__43(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__43', parent, True) as rule:
            current = rule.current
            current.src += '\"email\"'
        return current

    def T__44(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__44', parent, True) as rule:
            current = rule.current
            current.src += '\"team@example.com\"'
        return current

    def T__45(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__45', parent, True) as rule:
            current = rule.current
            current.src += '{}'
        return current

    def T__46(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__46', parent, True) as rule:
            current = rule.current
            current.src += '\"Project name?\"'
        return current

    def T__47(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__47', parent, True) as rule:
            current = rule.current
            current.src += '\"Use Docker?\"'
        return current

    def T__48(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__48', parent, True) as rule:
            current = rule.current
            current.src += '\"Choose a license\"'
        return current

    def T__49(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__49', parent, True) as rule:
            current = rule.current
            current.src += '\"Database settings\"'
        return current

    def T__50(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__50', parent, True) as rule:
            current = rule.current
            current.src += '\"Name of the generated package\"'
        return current

    def T__51(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__51', parent, True) as rule:
            current = rule.current
            current.src += '\"Owner metadata\"'
        return current

    def T__52(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__52', parent, True) as rule:
            current = rule.current
            current.src += '[]'
        return current

    def T__53(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__53', parent, True) as rule:
            current = rule.current
            current.src += '['
        return current

    def T__54(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__54', parent, True) as rule:
            current = rule.current
            current.src += '\"{{cookiecutter.repo_name}}/assets/*\"'
        return current

    def T__55(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__55', parent, True) as rule:
            current = rule.current
            current.src += ']'
        return current

    def T__56(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__56', parent, True) as rule:
            current = rule.current
            current.src += '\"{{cookiecutter.repo_name}}/rendered/*.yml\"'
        return current

    def T__57(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__57', parent, True) as rule:
            current = rule.current
            current.src += '\"\\n\"'
        return current

    def T__58(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__58', parent, True) as rule:
            current = rule.current
            current.src += '\"\\r\\n\"'
        return current

    def T__59(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__59', parent, True) as rule:
            current = rule.current
            current.src += 'null'
        return current

    def T__60(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__60', parent, True) as rule:
            current = rule.current
            current.src += '\"path\"'
        return current

    def T__61(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__61', parent, True) as rule:
            current = rule.current
            current.src += '\"kind\"'
        return current

    def T__62(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__62', parent, True) as rule:
            current = rule.current
            current.src += '\"text\"'
        return current

    def T__63(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__63', parent, True) as rule:
            current = rule.current
            current.src += '\"contents\"'
        return current

    def T__64(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__64', parent, True) as rule:
            current = rule.current
            current.src += '\"binary\"'
        return current

    def T__65(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__65', parent, True) as rule:
            current = rule.current
            current.src += '\"README.md\"'
        return current

    def T__66(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__66', parent, True) as rule:
            current = rule.current
            current.src += '\"docs/guide.md\"'
        return current

    def T__67(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__67', parent, True) as rule:
            current = rule.current
            current.src += '\"rendered/config.yml\"'
        return current

    def T__68(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__68', parent, True) as rule:
            current = rule.current
            current.src += '\"{{cookiecutter.repo_name}}/README.md\"'
        return current

    def T__69(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__69', parent, True) as rule:
            current = rule.current
            current.src += '\"{{cookiecutter.repo_name}}/pyproject.toml\"'
        return current

    def T__70(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__70', parent, True) as rule:
            current = rule.current
            current.src += '\"{{cookiecutter.repo_name}}/src/{{cookiecutter.repo_name}}/__init__.py\"'
        return current

    def T__71(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__71', parent, True) as rule:
            current = rule.current
            current.src += '\"{{cookiecutter.repo_name}}/templates/report.txt\"'
        return current

    def T__72(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__72', parent, True) as rule:
            current = rule.current
            current.src += '\"assets/logo.bin\"'
        return current

    def T__73(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__73', parent, True) as rule:
            current = rule.current
            current.src += '\"{{cookiecutter.repo_name}}/assets/logo.bin\"'
        return current

    def T__74(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__74', parent, True) as rule:
            current = rule.current
            current.src += '\"# {{ cookiecutter.project_name }}\\n\"'
        return current

    def T__75(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__75', parent, True) as rule:
            current = rule.current
            current.src += '\"package = {{ cookiecutter.repo_name }}\\n\"'
        return current

    def T__76(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__76', parent, True) as rule:
            current = rule.current
            current.src += '\"docs_enabled={{ cookiecutter.feature_flags.docs }}\\n\"'
        return current

    def T__77(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__77', parent, True) as rule:
            current = rule.current
            current.src += '\"engine={{ cookiecutter.database.engine }}\\n\"'
        return current

    def T__78(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__78', parent, True) as rule:
            current = rule.current
            current.src += '\"{{ cookiecutter.missing_value }}\\n\"'
        return current

    def T__79(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__79', parent, True) as rule:
            current = rule.current
            current.src += '\"AAECAwQ=\"'
        return current

    def T__80(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__80', parent, True) as rule:
            current = rule.current
            current.src += '\"c29tZS1iaW5hcnktYnl0ZXM=\"'
        return current

    def T__81(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__81', parent, True) as rule:
            current = rule.current
            current.src += '\"pre_prompt\"'
        return current

    def T__82(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__82', parent, True) as rule:
            current = rule.current
            current.src += '\"pre_gen_project\"'
        return current

    def T__83(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__83', parent, True) as rule:
            current = rule.current
            current.src += '\"post_gen_project\"'
        return current

    def T__84(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__84', parent, True) as rule:
            current = rule.current
            current.src += '\"from pathlib import Path\\nPath(\'HOOK_OK\').write_text(\'ok\', encoding=\'utf-8\')\\n\"'
        return current

    def T__85(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__85', parent, True) as rule:
            current = rule.current
            current.src += '\"raise SystemExit(1)\\n\"'
        return current

    def T__86(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__86', parent, True) as rule:
            current = rule.current
            current.src += '\"key\"'
        return current

    def T__87(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__87', parent, True) as rule:
            current = rule.current
            current.src += '\"title\"'
        return current

    def T__88(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__88', parent, True) as rule:
            current = rule.current
            current.src += '\"description\"'
        return current

    def T__89(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__89', parent, True) as rule:
            current = rule.current
            current.src += '\"core\"'
        return current

    def T__90(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__90', parent, True) as rule:
            current = rule.current
            current.src += '\"service\"'
        return current

    def T__91(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__91', parent, True) as rule:
            current = rule.current
            current.src += '\"nested_core\"'
        return current

    def T__92(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__92', parent, True) as rule:
            current = rule.current
            current.src += '\"nested_service\"'
        return current

    def T__93(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__93', parent, True) as rule:
            current = rule.current
            current.src += '\"Core Template\"'
        return current

    def T__94(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__94', parent, True) as rule:
            current = rule.current
            current.src += '\"Service Template\"'
        return current

    def T__95(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__95', parent, True) as rule:
            current = rule.current
            current.src += '\"Minimal local template\"'
        return current

    def T__96(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__96', parent, True) as rule:
            current = rule.current
            current.src += '\"Template with a nested prompt path\"'
        return current

    def T__97(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__97', parent, True) as rule:
            current = rule.current
            current.src += '\"no_input\"'
        return current

    def T__98(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__98', parent, True) as rule:
            current = rule.current
            current.src += 'true'
        return current

    def T__99(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__99', parent, True) as rule:
            current = rule.current
            current.src += '\"extra_context\"'
        return current

    def T__100(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__100', parent, True) as rule:
            current = rule.current
            current.src += '\"replay\"'
        return current

    def T__101(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__101', parent, True) as rule:
            current = rule.current
            current.src += '\"overwrite_if_exists\"'
        return current

    def T__102(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__102', parent, True) as rule:
            current = rule.current
            current.src += '\"skip_if_file_exists\"'
        return current

    def T__103(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__103', parent, True) as rule:
            current = rule.current
            current.src += '\"accept_hooks\"'
        return current

    def T__104(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__104', parent, True) as rule:
            current = rule.current
            current.src += '\"keep_project_on_failure\"'
        return current

    def T__105(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__105', parent, True) as rule:
            current = rule.current
            current.src += '\"output_dir_state\"'
        return current

    def T__106(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__106', parent, True) as rule:
            current = rule.current
            current.src += 'false'
        return current

    def T__107(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__107', parent, True) as rule:
            current = rule.current
            current.src += '\"Overwritten Project\"'
        return current

    def T__108(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__108', parent, True) as rule:
            current = rule.current
            current.src += '\"true\"'
        return current

    def T__109(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__109', parent, True) as rule:
            current = rule.current
            current.src += '\"cookiecutter\"'
        return current

    def T__110(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__110', parent, True) as rule:
            current = rule.current
            current.src += '\"replay_project\"'
        return current

    def T__111(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__111', parent, True) as rule:
            current = rule.current
            current.src += '\"MIT\"'
        return current

    def T__112(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__112', parent, True) as rule:
            current = rule.current
            current.src += '\"GPL\"'
        return current

    def T__113(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__113', parent, True) as rule:
            current = rule.current
            current.src += '\"Apache\"'
        return current

    def T__114(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__114', parent, True) as rule:
            current = rule.current
            current.src += '\"BSD\"'
        return current

    def T__115(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__115', parent, True) as rule:
            current = rule.current
            current.src += '\"missing\"'
        return current

    def T__116(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__116', parent, True) as rule:
            current = rule.current
            current.src += '\"existing_empty\"'
        return current

    def T__117(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__117', parent, True) as rule:
            current = rule.current
            current.src += '\"project_exists\"'
        return current


    _default_rule: ClassVar[Callable[['cookiecutter_caseGenerator', ParentRule | None], Rule]] = case_file

    _rule_sizes: ClassVar[dict[str, RuleSize]] = {
        'case_file': RuleSize(7, 139),
        'case_object': RuleSize(6, 139),
        'execution_mode': RuleSize(2, 1),
        'template_source': RuleSize(2, 1),
        'template_object': RuleSize(5, 91),
        'root_name': RuleSize(2, 1),
        'cookiecutter_json_object': RuleSize(3, 33),
        'project_name_value': RuleSize(2, 1),
        'repo_name_value': RuleSize(2, 1),
        'database_object': RuleSize(2, 9),
        'feature_flag_dict': RuleSize(3, 9),
        'owner_object': RuleSize(2, 9),
        'prompts_object': RuleSize(2, 1),
        'copy_without_render_array': RuleSize(2, 1),
        'newline_value': RuleSize(2, 1),
        'files_array': RuleSize(4, 15),
        'file_entry': RuleSize(3, 13),
        'path_expr': RuleSize(2, 1),
        'binary_path_expr': RuleSize(2, 1),
        'text_contents': RuleSize(2, 1),
        'binary_contents': RuleSize(2, 1),
        'hooks_object': RuleSize(3, 13),
        'hook_script': RuleSize(2, 1),
        'nested_templates_value': RuleSize(2, 1),
        'nested_template_entry': RuleSize(3, 17),
        'nested_key': RuleSize(2, 1),
        'nested_path': RuleSize(2, 1),
        'nested_title': RuleSize(2, 1),
        'nested_description': RuleSize(2, 1),
        'invocation_object': RuleSize(3, 33),
        'extra_context_object': RuleSize(2, 1),
        'replay_value': RuleSize(2, 1),
        'choice_array': RuleSize(2, 5),
        'output_dir_state': RuleSize(2, 1),
        'json_bool': RuleSize(2, 1),
        'T__0': RuleSize(1, 1),
        'T__1': RuleSize(1, 1),
        'T__2': RuleSize(1, 1),
        'T__3': RuleSize(1, 1),
        'T__4': RuleSize(1, 1),
        'T__5': RuleSize(1, 1),
        'T__6': RuleSize(1, 1),
        'T__7': RuleSize(1, 1),
        'T__8': RuleSize(1, 1),
        'T__9': RuleSize(1, 1),
        'T__10': RuleSize(1, 1),
        'T__11': RuleSize(1, 1),
        'T__12': RuleSize(1, 1),
        'T__13': RuleSize(1, 1),
        'T__14': RuleSize(1, 1),
        'T__15': RuleSize(1, 1),
        'T__16': RuleSize(1, 1),
        'T__17': RuleSize(1, 1),
        'T__18': RuleSize(1, 1),
        'T__19': RuleSize(1, 1),
        'T__20': RuleSize(1, 1),
        'T__21': RuleSize(1, 1),
        'T__22': RuleSize(1, 1),
        'T__23': RuleSize(1, 1),
        'T__24': RuleSize(1, 1),
        'T__25': RuleSize(1, 1),
        'T__26': RuleSize(1, 1),
        'T__27': RuleSize(1, 1),
        'T__28': RuleSize(1, 1),
        'T__29': RuleSize(1, 1),
        'T__30': RuleSize(1, 1),
        'T__31': RuleSize(1, 1),
        'T__32': RuleSize(1, 1),
        'T__33': RuleSize(1, 1),
        'T__34': RuleSize(1, 1),
        'T__35': RuleSize(1, 1),
        'T__36': RuleSize(1, 1),
        'T__37': RuleSize(1, 1),
        'T__38': RuleSize(1, 1),
        'T__39': RuleSize(1, 1),
        'T__40': RuleSize(1, 1),
        'T__41': RuleSize(1, 1),
        'T__42': RuleSize(1, 1),
        'T__43': RuleSize(1, 1),
        'T__44': RuleSize(1, 1),
        'T__45': RuleSize(1, 1),
        'T__46': RuleSize(1, 1),
        'T__47': RuleSize(1, 1),
        'T__48': RuleSize(1, 1),
        'T__49': RuleSize(1, 1),
        'T__50': RuleSize(1, 1),
        'T__51': RuleSize(1, 1),
        'T__52': RuleSize(1, 1),
        'T__53': RuleSize(1, 1),
        'T__54': RuleSize(1, 1),
        'T__55': RuleSize(1, 1),
        'T__56': RuleSize(1, 1),
        'T__57': RuleSize(1, 1),
        'T__58': RuleSize(1, 1),
        'T__59': RuleSize(1, 1),
        'T__60': RuleSize(1, 1),
        'T__61': RuleSize(1, 1),
        'T__62': RuleSize(1, 1),
        'T__63': RuleSize(1, 1),
        'T__64': RuleSize(1, 1),
        'T__65': RuleSize(1, 1),
        'T__66': RuleSize(1, 1),
        'T__67': RuleSize(1, 1),
        'T__68': RuleSize(1, 1),
        'T__69': RuleSize(1, 1),
        'T__70': RuleSize(1, 1),
        'T__71': RuleSize(1, 1),
        'T__72': RuleSize(1, 1),
        'T__73': RuleSize(1, 1),
        'T__74': RuleSize(1, 1),
        'T__75': RuleSize(1, 1),
        'T__76': RuleSize(1, 1),
        'T__77': RuleSize(1, 1),
        'T__78': RuleSize(1, 1),
        'T__79': RuleSize(1, 1),
        'T__80': RuleSize(1, 1),
        'T__81': RuleSize(1, 1),
        'T__82': RuleSize(1, 1),
        'T__83': RuleSize(1, 1),
        'T__84': RuleSize(1, 1),
        'T__85': RuleSize(1, 1),
        'T__86': RuleSize(1, 1),
        'T__87': RuleSize(1, 1),
        'T__88': RuleSize(1, 1),
        'T__89': RuleSize(1, 1),
        'T__90': RuleSize(1, 1),
        'T__91': RuleSize(1, 1),
        'T__92': RuleSize(1, 1),
        'T__93': RuleSize(1, 1),
        'T__94': RuleSize(1, 1),
        'T__95': RuleSize(1, 1),
        'T__96': RuleSize(1, 1),
        'T__97': RuleSize(1, 1),
        'T__98': RuleSize(1, 1),
        'T__99': RuleSize(1, 1),
        'T__100': RuleSize(1, 1),
        'T__101': RuleSize(1, 1),
        'T__102': RuleSize(1, 1),
        'T__103': RuleSize(1, 1),
        'T__104': RuleSize(1, 1),
        'T__105': RuleSize(1, 1),
        'T__106': RuleSize(1, 1),
        'T__107': RuleSize(1, 1),
        'T__108': RuleSize(1, 1),
        'T__109': RuleSize(1, 1),
        'T__110': RuleSize(1, 1),
        'T__111': RuleSize(1, 1),
        'T__112': RuleSize(1, 1),
        'T__113': RuleSize(1, 1),
        'T__114': RuleSize(1, 1),
        'T__115': RuleSize(1, 1),
        'T__116': RuleSize(1, 1),
        'T__117': RuleSize(1, 1),
    }

    _alt_sizes: ClassVar[tuple[tuple[RuleSize, ...], ...]] = (
        (RuleSize(1, 1), RuleSize(1, 1)),  # 0
        (RuleSize(2, 33), RuleSize(3, 33)),  # 1
        (RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1)),  # 2
        (RuleSize(1, 9), RuleSize(1, 9)),  # 3
        (RuleSize(1, 1), RuleSize(1, 17), RuleSize(1, 9)),  # 4
        (RuleSize(1, 1), RuleSize(1, 3), RuleSize(1, 3)),  # 5
        (RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1)),  # 6
        (RuleSize(3, 15), RuleSize(3, 29), RuleSize(3, 43)),  # 7
        (RuleSize(2, 13), RuleSize(2, 13)),  # 8
        (RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1)),  # 9
        (RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1)),  # 10
        (RuleSize(1, 1), RuleSize(3, 37)),  # 11
        (RuleSize(2, 33), RuleSize(2, 33)),  # 12
        (RuleSize(1, 1), RuleSize(1, 5), RuleSize(1, 5)),  # 13
        (RuleSize(1, 1), RuleSize(1, 17)),  # 14
        (RuleSize(1, 7), RuleSize(1, 5)),  # 15
    )

    _alt_conds: ClassVar[tuple[tuple[float, ...], ...]] = (
        (1, 1),  # 0
        (1, 1, 1, 1),  # 1
        (1, 1, 1),  # 2
        (1, 1, 1, 1, 1, 1, 1),  # 3
        (1, 1, 1, 1, 1),  # 4
    )

    _quant_sizes: ClassVar[tuple[RuleSize, ...]] = (
    )

    _charsets: ClassVar[tuple[tuple[int, ...], ...]] = (
        Generator._charset(((0x20, 0x7f), )),  # 0
    )
